// <!-- ============ SCENARIO DATA ============ -->
// Plan-driven Schlüsselfertigbau change recognition.
const SCENARIO = {
  product: {
    name: "Nachweis",
  },
  roles: [
    {
      id: "site",
      label: "Planprüfung",
      persona: "Projektleiter",
      device: "Desktop",
    },
    {
      id: "commercial",
      label: "Änderungsmitteilung",
      persona: "Projektteam / Kalkulation",
      device: "Desktop",
    },
    {
      id: "legal",
      label: "Freigabe",
      persona: "Gesamtprojektleiter",
      device: "Laptop",
    },
  ],
  project: "Neubau Laborgebäude · LP3-Vertragsbasis",
  workPackage: "Trockenbau / Brandschutz · Ebene 02",
  eventId: "REV‑08",
  claimId: "ÄM‑017",
  title: "F90-Anforderung statt F0-Wand",
  bausoll: {
    lv: "FLB 4.2.13 / Plan A‑203 Rev. 03",
    description: "Trennwand Achse B4 als F0 / ohne Brandschutzklassifizierung",
    quantity: "42 m Wandfläche",
    unitPrice: "Regelwand aus GU-Angebot",
    contract: "funktionale Leistungsbeschreibung + LP3-Planstand",
  },
  bauist: {
    description: "Brandschutzbericht Rev. 08 fordert F90-Wand mit zugelassener Tür",
    depth: "Achse B4 · Ebene 02",
    extraQuantity: "+42 m F90-Systemwand · +1 T30-RS Tür",
    method: "Planabgleich gegen Brandschutz, Bauphysik, FLB und alte Revision",
    order: "Änderungsmitteilung zur AG-Grundsatzentscheidung vorbereitet",
  },
  metadata: [
    "Planpaket Rev. 08 eingegangen",
    "19.06. · 10:42",
    "Revisionswolke bei Achse B4",
    "Ebene 02",
    "Bausoll-Prüfung 68%",
  ],
  note: "Die neue Planrevision markiert eine Änderung an Achse B4. Der Grundriss bleibt bei F0, der Brandschutzbericht fordert neu F90; offen ist, ob dies unter die Komplettheitsklausel fällt oder eine geänderte Leistung ist.",
  riskFlags: [
    "Komplettheitsklausel-Einwand wahrscheinlich",
    "Bauphysikkatalog noch nicht geprüft",
    "Ausführung startet in 9 Tagen",
  ],
  proofActions: [
    "Bauphysikkatalog prüfen",
    "alte Planrevision gegenüberstellen",
    "Änderungsmitteilung mit ca.-Kosten vorbereiten",
  ],
  pricing: {
    basis: "ca.-Kostenschätzung vor ITWO-Nachtrag",
    newPosition: "ÄM‑017 · F90-Systemwand + T30-RS Tür",
    devices: "Angebotsansätze + Nachunternehmer-Richtpreis",
    quantity: "42 m Wandfläche · 1 Tür",
    derivedEp: "≈ 690 €/m Wand + 3.200 € Tür",
    total: "32.200 €",
    argument: "vorläufige Größenordnung für AG-Grundsatzentscheidung",
  },
  legalChecks: [
    ["Bausoll-Dokumente vollständig geprüft", true],
    ["Widerspruch zwischen Plan und Bericht dokumentiert", true],
    ["Komplettheitsklausel-Risiko bewertet", false],
    ["Terminwirkung beschrieben", true],
    ["Änderungsmitteilung exportbereit", true],
  ],
  finalGap: "Formulierung schärfen: nicht fehlende GU-Fachkenntnis, sondern nachträgliche Konkretisierung aus Rev. 08.",
  documentSections: [
    "Änderungsmitteilung",
    "Kurzbeschreibung der Planänderung",
    "Bausoll-Matrix",
    "Revisionsvergleich Rev. 03 ↔ Rev. 08",
    "Komplettheitsklausel-Risiko",
    "ca.-Kosten / Terminwirkung",
    "Entscheidungsvorlage AG",
  ],
  voiceTranscript: "Neue Revision vom Brandschutzbericht ist eingegangen. In Achse B4 ist jetzt F90 gefordert, aber unser Vertragsplan zeigt dort nur F0. Bitte gegen FLB, Bauphysik und alte Revision prüfen und eine Änderungsmitteilung vorbereiten, bevor die Ausführung startet.",
  aiSummary: {
    what: "Planrevision fordert höherwertige Brandschutzwand",
    location: {
      bauteil: "Achse B4",
      geschoss: "Ebene 02",
      achse: "Raumtrennung Labor / Flur",
    },
    spiegel: {
      soll: "LP3-Vertragsplan Rev. 03 — Trennwand F0",
      ist: "Brandschutzbericht Rev. 08 — F90 + T30-RS Tür gefordert",
    },
    ursache: "plan_contradiction",
    instruction: "Revisionswolke Rev. 08 — Prüfung vor Ausführungsstart",
    terminauswirkung: {
      status: "delay",
      duration: "9 Tage bis Ausführung",
    },
  },
  smartActions: [
    { id: "action-plan", task: "Rev. 03 ↔ Rev. 08 vergleichen", icon: "📐", auto: true, source: "Planstand" },
    { id: "action-fire", task: "Brandschutzbericht prüfen", icon: "🔥", auto: true, source: "DMS" },
    { id: "action-physics", task: "Bauphysikkatalog prüfen", icon: "📚", auto: false },
    { id: "action-flb", task: "FLB-Leistung abgrenzen", icon: "📄", auto: false },
    { id: "action-cost", task: "ca.-Kosten schätzen", icon: "€", auto: false },
    { id: "action-notice", task: "Änderungsmitteilung vorbereiten", icon: "✉️", auto: false },
  ],
  demoWorkflow: {
    evidenceCards: [
      { id: "D01", type: "Vertragsplan", title: "A‑203 Rev. 03 · Wand B4 = F0", role: "Bausoll", supports: "Bausoll" },
      { id: "D02", type: "FLB", title: "FLB 4.2.13 · Standard-Trennwand", role: "Bausoll", supports: "Bausoll" },
      { id: "D03", type: "Brandschutz", title: "BSK Rev. 08 · F90 gefordert", role: "Neue Anforderung", supports: "Revision" },
      { id: "D04", type: "Bauphysik", title: "Katalog Raumabschluss prüfen", role: "offener Abgleich", supports: "Bausoll", note: "noch nicht geprüft" },
      { id: "D05", type: "Revisionsvergleich", title: "Revisionswolke Achse B4", role: "Änderungsauslöser", supports: "Revision" },
      { id: "D06", type: "Terminplan", title: "Trockenbau Start in 9 Tagen", role: "Timing", supports: "Entscheidung" },
    ],
    pricingRows: [
      { id: "C01", category: "Wand", description: "F90-Systemwand statt Standardwand", quantity: "42 m", unitRate: "690 €/m", amount: "28.980 €", priceBasis: "Angebotsansatz + NU-Richtpreis", evidence: ["D01", "D03"], risk: "yellow", weakness: "Richtpreis noch nicht als verbindliches NU-Angebot belegt", missingProof: "NU-Angebot für F90-Systemwand anfragen" },
      { id: "C02", category: "Tür", description: "T30-RS Tür inkl. Beschläge", quantity: "1 Stk.", unitRate: "3.200 €", amount: "3.200 €", priceBasis: "NU-Richtpreis", evidence: ["D03"], risk: "yellow", weakness: "Spezifikation Türblatt/Beschläge noch grob", missingProof: "Türanforderung aus Brandschutzbericht übernehmen" },
      { id: "C03", category: "Risiko", description: "Komplettheitsklausel-Abgrenzung", quantity: "1", unitRate: "intern", amount: "offen", priceBasis: "Bausoll-Matrix", evidence: ["D01", "D02", "D04"], risk: "red", weakness: "Bauphysik fehlt; AG kann argumentieren, ein erfahrener GU hätte F90 erkennen müssen", missingProof: "Bauphysikkatalog prüfen und Argumentation ergänzen" },
      { id: "C04", category: "Termin", description: "Umplanung / NU-Freigabe", quantity: "ca. 3–5 AT", unitRate: "Terminwirkung", amount: "kritisch", priceBasis: "Terminplan D06", evidence: ["D06"], risk: "yellow", weakness: "Ausführung beginnt in 9 Tagen", missingProof: "Entscheidungsfrist in Änderungsmitteilung setzen" },
    ],
    pricingTotal: "32.200 € netto ca.",
  },
};

const I18N = {
  en: {
    static: {
      brandTag: "Change-order management",
      navHint: "Keyboard: ← back · →/Enter next · R restart",
      back: "← Back",
      next: "Next →",
      restart: "Restart",
      restartNext: "Restart ↻",
      toast: "Change-order file exported as PDF",
    },
    replace: {
      "Neue Planrevision mit Nachtragspotenzial":
        "New plan revision with change-order potential",
      "Die neue Planrevision markiert eine Änderung an Achse B4. Der Grundriss bleibt bei F0, der Brandschutzbericht fordert neu F90; offen ist, ob dies unter die Komplettheitsklausel fällt oder eine geänderte Leistung ist.":
        "The new plan revision marks a change at axis B4. The floor plan still shows F0, but the fire-protection report now requires F90; it is open whether this falls under the completeness clause or is a changed service.",
      Planprüfung: "Plan review",
      "Neubau Laborgebäude": "New laboratory building",
      "LP3-Vertragsbasis": "LP3 contract basis",
      Revisionspaket: "Revision package",
      Unterlagen: "Documents",
      "Start Ausführung": "Execution start",
      Quelle: "Source",
      Planstand: "Plan version",
      Hinweis: "Note",
      "Grundriss A‑203": "Floor plan A‑203",
      Revisionswolke: "Revision cloud",
      "Achse B4 markiert": "Axis B4 marked",
      Brandschutzbericht: "Fire-protection report",
      Konflikt: "Conflict",
      "F90 statt F0": "F90 instead of F0",
      Bauphysikkatalog: "Building-physics catalog",
      "ungeprüft": "unchecked",
      "Raumabschluss offen": "Room enclosure open",
      "Workflow-Hinweis": "Workflow note",
      "Planänderung vor Baustelle": "Plan change before site",
      "Viele SF-Bau-Nachträge entstehen nicht erst auf der Baustelle, sondern wenn neue Pläne und Berichte eintreffen und gegen das Bausoll geprüft werden müssen.":
        "Many turnkey change orders arise not on site but when new plans and reports arrive and must be checked against the contracted scope.",
      "Bausoll = das A und O": "Contracted scope = everything",
      Komplettheitsklausel: "Completeness clause",
      "Revisionswolke prüfen": "Check revision cloud",
      "Revisionsvergleich": "Revision comparison",
      "Was hat sich gegenüber dem Vertragsstand geändert?":
        "What changed compared to the contract status?",
      "A‑203 Rev. 03 · Vertragsbasis": "A‑203 rev. 03 · contract basis",
      "BSK Rev. 08 · neue Anforderung": "BSK rev. 08 · new requirement",
      "Automatisch erkannt": "Automatically detected",
      "F0 ↔ F90 Widerspruch": "F0 ↔ F90 contradiction",
      "Bauphysik-Gegencheck fehlt": "Building-physics counter-check missing",
      "Bausoll-Abgleich starten": "Start contracted-scope comparison",
      "Planpaket wird strukturiert…": "Structuring plan package…",
      "Revision, Berichte und Bausoll werden abgeglichen":
        "Revision, reports and contracted scope are compared",
      "Nachweis ordnet die Änderung automatisch den Vertragsunterlagen zu.":
        "Nachweis maps the change to the contract documents automatically.",
      "KI-Triage": "AI triage",
      "Mögliche geänderte Leistung erkannt": "Possible changed service detected",
      "Planrevision fordert höherwertige Brandschutzwand":
        "Plan revision requires higher-grade fire-protection wall",
      "Ebene 02": "Level 02",
      "9 Tage bis Ausführung": "9 days until execution",
      "LP3-Vertragsplan Rev. 03 — Trennwand F0":
        "LP3 contract plan rev. 03 — partition F0",
      "Brandschutzbericht Rev. 08 — F90 + T30-RS Tür gefordert":
        "Fire-protection report rev. 08 — F90 + T30-RS door required",
      "Revisionswolke Rev. 08 — Prüfung vor Ausführungsstart":
        "Revision cloud rev. 08 — review before execution start",
      "Prüfaufgaben": "Review tasks",
      "Neue Revision": "New revision",
      "Rev. 03 ↔ Rev. 08 vergleichen": "Compare rev. 03 ↔ rev. 08",
      "Brandschutzbericht prüfen": "Check fire-protection report",
      "Bauphysikkatalog prüfen": "Check building-physics catalog",
      "FLB-Leistung abgrenzen": "Delimit FLB scope",
      "ca.-Kosten schätzen": "Estimate approx. cost",
      "Änderungsmitteilung vorbereiten": "Prepare change notice",
      "An Projektteam übergeben": "Hand off to project team",
      "Bausoll-Nachweis": "Contracted-scope evidence",
      "Die Änderungsmitteilung wird nicht aus Baustellenfotos gebaut, sondern aus dem prüfbaren Abgleich aller relevanten Plan- und Vertragsunterlagen.":
        "The change notice is built not from site photos but from the auditable comparison of all relevant plan and contract documents.",
      "Bausoll-Prüfung": "Contracted-scope check",
      "geprüft": "checked",
      "Bauphysik geprüft": "Building physics checked",
      "Bauphysik prüfen": "Check building physics",
      "Vertragsplan": "Contract plan",
      Brandschutz: "Fire protection",
      Bauphysik: "Building physics",
      Terminplan: "Schedule",
      "A‑203 Rev. 03 · Wand B4 = F0": "A‑203 rev. 03 · wall B4 = F0",
      "FLB 4.2.13 · Standard-Trennwand": "FLB 4.2.13 · standard partition",
      "BSK Rev. 08 · F90 gefordert": "BSK rev. 08 · F90 required",
      "Katalog Raumabschluss prüfen": "Check room-enclosure catalog",
      "Revisionswolke Achse B4": "Revision cloud axis B4",
      "Trockenbau Start in 9 Tagen": "Drywall start in 9 days",
      "Neue Anforderung": "new requirement",
      "offener Abgleich": "open comparison",
      "Änderungsauslöser": "change trigger",
      Entscheidung: "decision",
      "noch nicht geprüft": "not yet checked",
      "Änderungsmitteilung vorbereiten · ": "Prepare change notice · ",
      "F90-Systemwand statt Standardwand":
        "F90 system wall instead of standard wall",
      "T30-RS Tür inkl. Beschläge": "T30-RS door incl. hardware",
      "Komplettheitsklausel-Abgrenzung": "Completeness-clause delimitation",
      "Umplanung / NU-Freigabe": "Replanning / subcontractor sign-off",
      "kritisch": "critical",
      "Richtpreis noch nicht als verbindliches NU-Angebot belegt":
        "Guide price not yet backed by a binding subcontractor quote",
      "Spezifikation Türblatt/Beschläge noch grob":
        "Door-leaf/hardware specification still rough",
      "Bauphysik fehlt; AG kann argumentieren, ein erfahrener GU hätte F90 erkennen müssen":
        "Building physics missing; client can argue an experienced GC should have recognized F90",
      "Ausführung beginnt in 9 Tagen": "Execution begins in 9 days",
      "NU-Angebot für F90-Systemwand anfragen":
        "Request subcontractor quote for F90 system wall",
      "Türanforderung aus Brandschutzbericht übernehmen":
        "Adopt door requirement from fire-protection report",
      "Bauphysikkatalog prüfen und Argumentation ergänzen":
        "Check building-physics catalog and add reasoning",
      "Entscheidungsfrist in Änderungsmitteilung setzen":
        "Set decision deadline in change notice",
      "geklärt": "resolved",
      Komplettheitsrisiko: "Completeness risk",
      Entscheidungsvorlage: "Decision template",
      "Risikoargument ergänzt": "Risk argument added",
      "Komplettheitsargument ergänzen": "Add completeness argument",
      "ca.-Kostenschätzung vor ITWO-Nachtrag":
        "approx. cost estimate before ITWO change order",
      "Zur Freigabe übergeben": "Hand off for approval",
      "Änderungsmitteilung freigegeben": "Change notice approved",
      "Die Entscheidungsvorlage ist bereit für Export und AG-Abstimmung.":
        "The decision template is ready for export and client coordination.",
      "vor Ausführung": "before execution",
      "Änderungsmitteilung exportieren (PDF)": "Export change notice (PDF)",
      "Kurzbeschreibung der Planänderung": "Brief description of the plan change",
      "Bausoll-Matrix": "Contracted-scope matrix",
      "Revisionsvergleich Rev. 03 ↔ Rev. 08":
        "Revision comparison rev. 03 ↔ rev. 08",
      "Komplettheitsklausel-Risiko": "Completeness-clause risk",
      "ca.-Kosten / Terminwirkung": "approx. cost / schedule impact",
      "Entscheidungsvorlage AG": "Client decision template",
      "ca.-Kosten": "approx. cost",
      "F90-Anforderung statt F0-Wand": "F90 requirement instead of F0 wall",
      "Änderungsmitteilung": "Change notice",
      Projektleiter: "Project lead",
      "Projektteam / Kalkulation": "Project team / costing",
      Gesamtprojektleiter: "Overall project lead",
      "Baufeld B": "Building Site B",
      "Erdarbeiten, UK −2,40 m": "Excavation, UK −2.40 m",
      "Achse A3–A7": "Axis A3–A7",
      "Fels / stark verfestigter Boden BK 6–7 angetroffen": "rock / strongly compacted soil class 6–7 encountered",
      "Planausschnitt markieren": "Mark plan excerpt",
      "Verortung": "Location",
      "Bauteil": "Building Part",
      "Geschoss": "Floor",
      "Achse": "Axis",
      "Soll-Ist-Abgleich": "Soll/Ist Comparison",
      "Soll": "Soll",
      "Ist": "Ist",
      "Ursache": "Cause",
      "Anordnung durch AG / Architekt": "Instruction by Client / Architect",
      "Geänderte Gegebenheiten vor Ort": "Changed local conditions",
      "Widerspruch in Planungsunterlagen": "Contradiction in planning documents",
      "Sonstiges": "Other",
      "Termin": "Schedule",
      "Verzögerung erwartet": "Delay expected",
      "2–3 Tage Verzögerung erwartet": "2–3 days delay expected",
      "Keine Verzögerung": "No delay",
      "Wir haben beim Aushub auf minus zwei vierzig Fels angetroffen. Das war nicht im LV vorgesehen, da steht nur Bodenklasse drei bis fünf. Der Bauleiter hat angeordnet, dass wir mit nem größeren Bagger und Meißel weitermachen. Die Anordnung ist BL-44. Die Felskante zieht sich quer durch die ganze Baugrube B.":
        "During excavation, we encountered rock at minus two forty. That was not in the BoQ, it only says soil excavation class three to five. The site manager instructed us to continue with a larger excavator and a breaker. The instruction is BL-44. The rock edge runs across the entire foundation pit B.",
      "Fels / stark verfestigter Boden (BK 6–7)":
        "rock / strongly compacted soil (class 6-7)",
      "Baugrube B, Tiefe −2,40 m":
        "foundation pit B, depth −2.40 m",
      "LV 02.03.0010 — Bodenaushub Bodenklasse 3–5":
        "LV 02.03.0010 — Soil excavation class 3–5",
      "Tatsächliche Bodenklasse weicht vom LV ab":
        "Actual soil class deviates from bill of quantities",
      "BL-44 — Fortführung mit Meißelverfahren":
        "BL-44 — continuation with breaker method",
      "+1.000 m³ Mehraushub":
        "+1,000 m³ additional excavation",
      "Foto der Felskante mit Maßstab":
        "photo of the rock edge with scale",
      "Tiefenmessung verifiziert":
        "depth measurement verified",
      "Tiefenmessung bestätigen (−2,40 m)":
        "confirm depth measurement (−2.40 m)",
      "Anordnung BL-44 verknüpfen":
        "link instruction BL-44",
      "GPS-Position erfasst":
        "GPS location captured",
      "Wetter & Bedingungen":
        "weather & conditions",
      "Sprich frei über das Ereignis...":
        "Speak freely about the event...",
      "Aufnahme läuft...":
        "Recording in progress...",
      "Sprachaufzeichnung":
        "Voice recording",
      "Sprachnotiz & Protokoll":
        "Voice note & transcript",
      "Rissbildung Bodenplatte A1":
        "Crack formation base slab A1",
      "Mögliche Abweichung":
        "Possible deviation",
      "Foto aufnehmen":
        "Take photo",
      "Was":
        "What",
      "Vollständiger Nachweis (100%)":
        "Complete evidence (100%)",
      "Beschreibe die Abweichung":
        "Describe the deviation",
      "Entwurf wird erstellt...":
        "Preparing draft...",
      "Strukturierung...":
        "Structuring...",
      "Sprachaufnahme wird verarbeitet...":
        "Processing voice recording...",
      "Analyse läuft...":
        "Analyzing...",
      "Erforderliche Nachweise":
        "Required evidence",
      "Sprachaufzeichnung beenden":
        "Stop recording",
      "Abweichung melden":
        "Report deviation",
      "Aufgabe: Foto der Felskante mit Maßstab":
        "Task: Photo of rock edge with scale",
      "Abweichung aufnehmen":
        "Record deviation",
      "Automatisch":
        "Auto",
      "Sensor":
        "Sensor",
      "Technischer Nachtrag": "Technical change order",
      "Aktueller Nachtrag": "Active change order",
      "Neubau Verwaltungsgebäude · Baufeld B":
        "New administrative building · Site B",
      "Aushub Baugrube · Tiefbau": "Foundation pit excavation · civil works",
      "Felsaushub Baufeld B": "Rock excavation · Site B",
      "Bodenaushub Bodenklasse 3–5": "Soil excavation class 3–5",
      "geschuldete Leistung laut LV": "contracted scope per bill of quantities",
      "Fels / stark verfestigter Boden BK 6–7":
        "rock / strongly compacted soil class 6–7",
      "größerer Bagger + Meißelverfahren": "larger excavator + breaker method",
      "Anordnung BL‑44 verknüpft": "instruction BL‑44 linked",
      "Wetter trocken": "weather dry",
      "Baugrube B": "foundation pit B",
      "Tiefe −2,40 m": "depth −2.40 m",
      "Rissbildung Bodenplatte A1": "crack formation base slab A1",
      "Felskante läuft quer durch Baugrube B. Aushub mit Standardgerät nicht fortsetzbar; Bauleiter ordnet Fortführung mit Meißel an.":
        "The rock edge runs across foundation pit B. Excavation cannot continue with standard equipment; the site manager orders continuation with a breaker.",
      "Nachweis Tiefenmaß fehlt": "depth measurement proof missing",
      "Frist Nachtragsankündigung § 2 Abs. 5 VOB/B in 4 Tagen":
        "change-order notice deadline § 2(5) VOB/B in 4 days",
      "LV-Bezug bestätigen": "confirm bill-of-quantities reference",
      "Tiefenmaß-Aufmaß anhängen": "attach depth measurement record",
      "Nachtragsankündigung als versendet markieren":
        "mark change-order notice as sent",
      "Urkalkulation fortschreiben": "extend the original cost calculation",
      "NT‑02.03.F · Felsaushub BK 6–7":
        "CO‑02.03.F · rock excavation class 6–7",
      "Geräte-/Lohnansätze aus Urkalkulation":
        "equipment/labor rates from original calculation",
      "der Höhe nach belastbar": "defensible on quantum",
      Kausalität: "causality",
      "Fristwahrung (§ 2 Abs. 5 VOB/B)": "deadline preserved (§ 2(5) VOB/B)",
      "LV-/Vertragsbezug": "BoQ/contract reference",
      Urkalkulationsbezug: "original-calculation reference",
      "Nachweise vollständig": "Evidence complete",
      "Gegengezeichnete Anordnung BL‑44 in Begründung referenzieren":
        "reference countersigned instruction BL‑44 in the justification",
      Deckblatt: "cover sheet",
      Sachverhalt: "facts",
      "Bausoll / Bau-Ist": "contracted scope / actual site condition",
      Nachweise: "evidence",
      Mengen: "quantities",
      "Kalkulation / Urkalkulationsbezug":
        "calculation / original-cost reference",
      "Begründung § 2 VOB/B": "justification § 2 VOB/B",
      Bausoll: "contracted scope",
      "Bau-Ist": "actual site condition",
      Abweichung: "deviation",
      Nachtragsakte: "change-order file",
      Nachtrag: "change order",
      Baustelle: "Site",
      Kaufmännisch: "Commercial",
      Recht: "Legal",
      "Polier / Bauleiter": "foreman / site manager",
      "KBL / Projektleitung": "commercial project lead",
      "Legal / Nachtragsmanager": "legal / change-order manager",
      Übergabe: "handoff",
      Mobile: "mobile",
      Desktop: "desktop",
      Laptop: "laptop",
      "Ereignisse Baustelle": "site events",
      Ereignisse: "events",
      Ereignis: "event",
      Polier: "foreman",
      "+ Ereignis erfassen": "+ Capture event",
      Heute: "Today",
      Neu: "New",
      Prüfung: "Review",
      Entwurf: "Draft",
      Info: "Info",
      OK: "OK",
      "Kamera · Auto-Metadaten": "Camera · auto metadata",
      "Felskante dokumentieren": "Document rock edge",
      "Mögliche Abweichung erkannt": "Possible deviation detected",
      "Das Ereignis passt zu": "This event matches",
      "Dokumentiere jetzt, was später prüffähig sein muss.":
        "Document now what must be auditable later.",
      "Dokumentiere jetzt, was später": "Document now what must later be",
      "was später prüffähig sein muss.": "what must be auditable later.",
      "prüffähig sein muss.": "must be auditable.",
      Dokumentiere: "Document",
      Notiz: "note",
      "An Kaufmännisch übergeben": "Hand off to Commercial",
      Übermittelt: "Transmitted",
      erfasst: "captured",
      "Übergabe anzeigen": "Show handoff",
      "Übergabe an die kaufmännische Leitung": "Handoff to the commercial lead",
      "Nachtrag-Dashboard": "change-order dashboard",
      "Offene Nachträge": "Open change orders",
      offen: "open",
      Volumen: "volume",
      Fristen: "deadlines",
      Titel: "title",
      Status: "status",
      Frist: "deadline",
      Wert: "value",
      "Mehrstahl Decke C": "additional rebar slab C",
      Tage: "days",
      "Provisorische Entwässerung": "temporary drainage",
      "Eingang von Baustelle": "incoming from site",
      öffnen: "open",
      "N‑204 öffnen": "Open N‑204",
      "Bausoll ↔ Bau-Ist": "Contracted scope ↔ actual condition",
      "ABW.": "DEV.",
      Leistung: "scope item",
      Menge: "quantity",
      Befund: "finding",
      Tiefe: "depth",
      Mehrmenge: "additional quantity",
      Verfahren: "method",
      "Foto Felskante": "rock-edge photo",
      Anordnung: "instruction",
      "Tiefenmaß?": "depth proof?",
      Vollständigkeit: "completeness",
      "Nachweise prüfen": "Check evidence",
      "Fehlende Nachweise zeigen": "show missing evidence",
      "Nachweise vervollständigen": "Complete evidence",
      "Nachweise vollständig": "Evidence complete",
      "Fehlende Nachweise ergänzen": "Add missing evidence",
      "Urkalkulation-Fortschreibung": "Original-cost extension",
      "Neue Position": "new item",
      "abgeleiteter EP": "derived unit price",
      "Damit ist der Nachtrag nicht nur dem Grunde nach plausibel, sondern":
        "This makes the change order plausible not only on entitlement, but also",
      "Nachtragssumme ≈": "change-order amount ≈",
      "Zur rechtlichen Prüfung übergeben": "Hand off to legal review",
      "rechtlichen Prüfung": "legal review",
      "95 % bereit": "95% ready",
      "Abweichung, Nachweise, Mengen und Urkalkulationsbezug sind strukturiert. Die Akte geht jetzt an Recht zur rechtlichen Freigabe.":
        "Deviation, evidence, quantities and original-cost reference are structured. The file now goes to Legal for sign-off.",
      "Die Akte geht jetzt an Recht zur rechtlichen Freigabe.":
        "The file now goes to Legal for sign-off.",
      "rechtlichen Freigabe": "legal sign-off",
      "Bausoll/Bau-Ist geklärt": "scope/actual comparison resolved",
      "Frist gewahrt": "deadline preserved",
      "An Recht übergeben": "Hand off to Legal",
      "Rechtliche Freigabe": "Legal sign-off",
      Freigabe: "Approval",
      "Freigabe-Queue": "approval queue",
      "1 Nachtragsakte zur Freigabe": "1 change-order file for approval",
      "1 offener Prüfpunkt": "1 open review item",
      Öffnen: "Open",
      "Rechtliche Prüfung": "Legal review",
      "Belastbarkeit prüfen": "Review defensibility",
      "1 offen": "1 open",
      "Formulierung bestätigen": "Confirm wording",
      "Letzter Prüfpunkt erledigt": "Final review item completed",
      Begründungsentwurf: "Draft justification",
      "Die angetroffene Bodenklasse": "The encountered soil class",
      "weicht vom vertraglich geschuldeten": "deviates from the contracted",
      " ab. Die geänderte Leistung wurde angeordnet und fristgerecht angekündigt.":
        ". The changed work was instructed and announced within the deadline.",
      "Die geänderte Leistung wurde angeordnet und fristgerecht angekündigt.":
        "The changed work was instructed and announced within the deadline.",
      "geänderte Leistung": "changed work",
      angeordnet: "instructed",
      fristgerecht: "within the deadline",
      "Als belastbar bestätigen & freigeben": "Confirm defensible & approve",
      "Belastbar – freigegeben": "Defensible – approved",
      "Die prüffähige Nachtragsakte ist bereit für Export und Versand.":
        "The auditable change-order file is ready for export and dispatch.",
      "Legal sign-off": "legal sign-off",
      "Nachtragsakte exportieren (PDF)": "Export change-order file (PDF)",
      Weiter: "Next",
      Dokumentvorschau: "document preview",
      "Prüffähige Nachtragsakte": "Auditable change-order file",
      Prüffähige: "auditable",
      enthalten: "included",
      Nachtragssumme: "change-order amount",
      "Das Baustellenereignis wurde klassifiziert und die Nachweise den Prüfkategorien zugeordnet.":
        "The site event has been classified and evidence assigned to review categories.",
      "dem Grunde nach": "on entitlement",
      "der Höhe nach": "on quantum",
      "Anspruchsbegründung": "Entitlement basis",
      "Preisnachweis": "Pricing evidence",
      "Fotos": "Photos",
      "Aufmaß": "Measurement record",
      "Urkalkulation": "Original costing",
      "Kein Nachweis": "No evidence",
      "Kritisch": "Critical",
      "Offen": "Open",
      "Nachweisstruktur": "Evidence structure",
      "Kostennachweis": "Cost evidence",
      "Fotos Felskante + Maßstab": "Rock edge photos + scale",
      "BL-44 Meißelverfahren": "BL-44 breaker method",
      "Geräte-/Lohnansätze": "equipment/labor rates",
      "Preisbasis": "price basis",
      "Keine AG-Gegenzeichnung": "No client countersignature",
      "Nicht AG-bestätigt": "Not confirmed by client",
      "Meißelarbeiten, Kolonne": "Chiseling work, crew",
      "30t Bagger + Hydraulikhammer": "30t excavator + hydraulic hammer",
      "Radlader Materialtransport": "Wheel loader transport",
      "Abtransport Felsgestein": "Rock material removal",
      "Nebenarbeiten pauschal": "Incidental work lump sum",
      "BGK / AGK / Wagnis & Gewinn": "Site overhead / company overhead / risk & profit",
      "Regiebericht nicht gegengezeichnet": "Site report not countersigned",
      "Gerätestunden nicht bestätigt": "Equipment hours not confirmed",
      "Nicht gegengezeichnet": "Not countersigned",
      "Aufmaß nicht AG-bestätigt": "Measurement record not confirmed by client",
      "Pauschalposition ohne belastbaren Nachweis": "Lump-sum item without traceable evidence",
      "Zuschlagslogik nur teilweise nachvollziehbar": "Surcharge logic only partially traceable",
      "BÜ-Gegenzeichnung Regiebericht anfordern": "Request countersignature on site report",
      "Stundenfreigabe oder BÜ-Bestätigung ergänzen": "Add hour release or site confirmation",
      "Regiebericht gegenzeichnen lassen": "Have site report countersigned",
      "Aufmaß bestätigen lassen": "Have measurement record confirmed",
      "Tätigkeiten aufschlüsseln oder Nachweis ergänzen": "Break down activities or add evidence",
      "EFB-Bezug und Zuschlagsbasis erläutern": "Clarify EFB reference and surcharge basis",
      "LV-Auszug": "BoQ extract",
      "Anordnung / Protokoll": "Instruction / minutes",
      "Regiebericht Meißelarbeiten": "Site report chiseling work",
      "Regiebericht": "Site report",
      "Aufwand": "Effort",
      "Gegenzeichnung angefordert": "Countersignature requested",
      "AG-Gegenzeichnung angefordert": "Client countersignature requested",
      "Fehlende Gegenzeichnung anfordern": "Request missing countersignature",
      "Aufgeschlüsselt": "Itemized",
      "Belegt": "Documented",
      "Urkalkulation fortgeschrieben": "Original costing extended",
      "Neu starten": "Start over",
      "AUTO: GPS · ZEIT · TIEFE": "AUTO: GPS · TIME · DEPTH",
      "app.nachweis.bau/nachtraege": "app.nachweis.bau/change-orders",
      "app.nachweis.bau/freigabe": "app.nachweis.bau/approval",
      SHOT: "SHOT",
      FOTO: "PHOTO",
    },
  },
  de: {
    static: {
      brandTag: "Nachtragsmanagement",
      navHint: "Tastatur: ← zurück · →/Enter weiter · R Neustart",
      back: "← Zurück",
      next: "Weiter →",
      restart: "Restart",
      restartNext: "Neu starten ↻",
      toast: "Änderungsmitteilung als PDF exportiert",
    },
    replace: {},
  },
};

let currentLanguage = "de";
