// <!-- ============ SCENARIO DATA ============ -->
// Swap this object to replace the synthetic Nachtrag without touching layout code.
const SCENARIO = {
  product: {
    name: "Nachweis",
    tagline: "Vom Bausoll-Abgleich zur prüffähigen Nachtragsakte.",
    context: "Ein Nachtrag. Drei Rollen. Drei Geräte.",
  },
  roles: [
    {
      id: "site",
      label: "Baustelle",
      persona: "Polier / Bauleiter",
      device: "Mobile",
    },
    {
      id: "commercial",
      label: "Kaufmännisch",
      persona: "KBL / Projektleitung",
      device: "Desktop",
    },
    {
      id: "legal",
      label: "Recht",
      persona: "Legal / Nachtragsmanager",
      device: "Laptop",
    },
  ],
  project: "Neubau Verwaltungsgebäude · Baufeld B",
  workPackage: "Aushub Baugrube · Tiefbau",
  eventId: "E‑118",
  claimId: "N‑204",
  title: "Felsaushub Baufeld B",
  oneLine:
    "Beim Aushub der Baugrube wird auf −2,40 m Fels / stark verfestigter Boden angetroffen — nicht im LV vorgesehen.",
  bausoll: {
    lv: "LV 02.03.0010",
    description: "Bodenaushub Bodenklasse 3–5",
    quantity: "≈ 800 m³",
    unitPrice: "12,40 €/m³",
    contract: "geschuldete Leistung laut LV",
  },
  bauist: {
    description: "Fels / stark verfestigter Boden BK 6–7",
    depth: "−2,40 m",
    extraQuantity: "+1.000 m³",
    method: "größerer Bagger + Meißelverfahren",
    order: "Anordnung BL‑44 verknüpft",
  },
  metadata: [
    "GPS 52.51°N, 13.40°E",
    "07.06. · 09:14",
    "Wetter trocken",
    "Baugrube B",
    "Tiefe −2,40 m",
  ],
  siteEvents: [
    ["07:42", "LKW-Zufahrt Nord blockiert", "Info"],
    ["08:55", "Aufmaß Schalung Abschnitt B2", "OK"],
    ["09:14", "Rissbildung Bodenplatte A1", "Neu"],
  ],
  guidedChecks: [
    ["Foto mit Maßstab", true],
    ["Tiefe dokumentiert", true],
    ["Anordnung verknüpfen", false],
    ["kurze Notiz ergänzen", false],
  ],
  note: "Felskante läuft quer durch Baugrube B. Aushub mit Standardgerät nicht fortsetzbar; Bauleiter ordnet Fortführung mit Meißel an.",
  riskFlags: [
    "Nachweis Tiefenmaß fehlt",
    "Frist Nachtragsankündigung § 2 Abs. 5 VOB/B in 4 Tagen",
    "LV-Bezug bestätigen",
  ],
  proofActions: [
    "LV-Bezug bestätigen",
    "Tiefenmaß-Aufmaß anhängen",
    "Nachtragsankündigung als versendet markieren",
  ],
  pricing: {
    basis: "Urkalkulation fortschreiben",
    newPosition: "NT‑02.03.F · Felsaushub BK 6–7",
    devices: "Geräte-/Lohnansätze aus Urkalkulation",
    quantity: "+1.000 m³",
    derivedEp: "28,50 €/m³",
    total: "28.500 €",
    argument: "der Höhe nach belastbar",
  },
  legalChecks: [
    ["Kausalität", true],
    ["Fristwahrung (§ 2 Abs. 5 VOB/B)", true],
    ["LV-/Vertragsbezug", true],
    ["Urkalkulationsbezug", true],
    ["Nachweise vollständig", false],
  ],
  finalGap: "Gegengezeichnete Anordnung BL‑44 in Begründung referenzieren",
  documentSections: [
    "Deckblatt",
    "Sachverhalt",
    "Bausoll / Bau-Ist",
    "Nachweise",
    "Mengen",
    "Kalkulation / Urkalkulationsbezug",
    "Begründung § 2 VOB/B",
  ],
  voiceTranscript: "Wir haben beim Aushub auf minus zwei vierzig Fels angetroffen. Das war nicht im LV vorgesehen, da steht nur Bodenklasse drei bis fünf. Der Bauleiter hat angeordnet, dass wir mit nem größeren Bagger und Meißel weitermachen. Die Anordnung ist BL-44. Die Felskante zieht sich quer durch die ganze Baugrube B.",
  aiSummary: {
    what: "Fels / stark verfestigter Boden (BK 6–7)",
    location: {
      bauteil: "Baufeld B",
      geschoss: "Erdarbeiten, UK −2,40 m",
      achse: "Achse A3–A7",
    },
    spiegel: {
      soll: "LV 02.03.0010 — Bodenaushub Bodenklasse 3–5",
      ist: "Fels / stark verfestigter Boden BK 6–7 angetroffen",
    },
    ursache: "changed_conditions",
    instruction: "BL-44 — Fortführung mit Meißelverfahren",
    terminauswirkung: {
      status: "delay",
      duration: "2–3 Tage",
    },
  },
  smartActions: [
    { id: "action-photo", task: "Foto der Felskante mit Maßstab", icon: "📸", auto: false },
    { id: "action-plan", task: "Planausschnitt markieren", icon: "📐", auto: false },
    { id: "action-depth", task: "Tiefenmessung verifiziert", icon: "📏", auto: true, source: "GPS" },
    { id: "action-instruction", task: "Anordnung BL-44 verknüpfen", icon: "📎", auto: false },
    { id: "action-gps", task: "GPS-Position erfasst", icon: "📍", auto: true, source: "GPS" },
    { id: "action-weather", task: "Wetter & Bedingungen", icon: "🌤️", auto: true, source: "Sensor" },
  ],
  spine: [
    "Bausoll",
    "Bau-Ist",
    "Abweichung",
    "Nachweise",
    "Menge/Kosten",
    "prüffähige Nachtragsakte",
  ],
  demoWorkflow: {
    evidenceCards: [
      { id: "A02", type: "LV-Auszug", title: "LV 02.03.0010", role: "Bausoll", supports: "dem Grunde nach" },
      { id: "A06", type: "Fotos", title: "Fotos Felskante + Maßstab", role: "Bau-Ist", supports: "dem Grunde nach" },
      { id: "A07", type: "Anordnung / Protokoll", title: "BL-44 Meißelverfahren", role: "Anordnung", supports: "dem Grunde nach", note: "Keine AG-Gegenzeichnung" },
      { id: "A10", type: "Aufmaß", title: "+1.000 m³ Mehraushub", role: "Menge", supports: "der Höhe nach", note: "Nicht AG-bestätigt" },
      { id: "A04", type: "Urkalkulation", title: "Geräte-/Lohnansätze", role: "Preisbasis", supports: "der Höhe nach" },
    ],
    pricingRows: [
      { id: "P01", category: "Lohn", description: "Meißelarbeiten, Kolonne", quantity: "68 h", unitRate: "68,00 €/h", amount: "4.624,00 €", priceBasis: "Regiebericht A09", evidence: ["A09"], risk: "yellow", weakness: "Regiebericht nicht gegengezeichnet", missingProof: "BÜ-Gegenzeichnung Regiebericht anfordern" },
      { id: "P02", category: "Gerät", description: "30t Bagger + Hydraulikhammer", quantity: "55 h", unitRate: "215,00 €/h", amount: "11.825,00 €", priceBasis: "Regiebericht A09 / Urkalkulation A04", evidence: ["A09", "A04"], risk: "yellow", weakness: "Gerätestunden nicht bestätigt", missingProof: "Stundenfreigabe oder BÜ-Bestätigung ergänzen" },
      { id: "P03", category: "Gerät", description: "Radlader Materialtransport", quantity: "16 h", unitRate: "115,00 €/h", amount: "1.840,00 €", priceBasis: "Regiebericht A09", evidence: ["A09"], risk: "yellow", weakness: "Nicht gegengezeichnet", missingProof: "Regiebericht gegenzeichnen lassen" },
      { id: "P04", category: "Transport", description: "Abtransport Felsgestein", quantity: "1.000 m³", unitRate: "4,50 €/m³", amount: "4.500,00 €", priceBasis: "Aufmaß A10", evidence: ["A10"], risk: "yellow", weakness: "Aufmaß nicht AG-bestätigt", missingProof: "Aufmaß bestätigen lassen" },
      { id: "P05", category: "Nebenarbeiten", description: "Nebenarbeiten pauschal", quantity: "1", unitRate: "580,00 €", amount: "580,00 €", priceBasis: "Pauschalansatz", evidence: [], risk: "red", weakness: "Pauschalposition ohne belastbaren Nachweis", missingProof: "Tätigkeiten aufschlüsseln oder Nachweis ergänzen" },
      { id: "P06", category: "Zuschläge", description: "BGK / AGK / Wagnis & Gewinn", quantity: "22%", unitRate: "auf EKT", amount: "5.141,18 €", priceBasis: "Urkalkulation / EFB A04", evidence: ["A04", "A12"], risk: "yellow", weakness: "Zuschlagslogik nur teilweise nachvollziehbar", missingProof: "EFB-Bezug und Zuschlagsbasis erläutern" },
    ],
    pricingTotal: "28.510 € netto",
  },
};

const I18N = {
  en: {
    static: {
      brandTag: "Change-order management",
      navHint: "Keyboard: ← back · →/Enter next · R restart",
      back: "← Back",
      next: "Next →",
      restart: "Restart",
      restartNext: "Restart ↻",
      toast: "Change-order file exported as PDF",
    },
    replace: {
      "Baufeld B": "Building Site B",
      "Erdarbeiten, UK −2,40 m": "Excavation, UK −2.40 m",
      "Achse A3–A7": "Axis A3–A7",
      "Fels / stark verfestigter Boden BK 6–7 angetroffen": "rock / strongly compacted soil class 6–7 encountered",
      "Planausschnitt markieren": "Mark plan excerpt",
      "Verortung": "Location",
      "Bauteil": "Building Part",
      "Geschoss": "Floor",
      "Achse": "Axis",
      "Soll-Ist-Abgleich": "Soll/Ist Comparison",
      "Soll": "Soll",
      "Ist": "Ist",
      "Ursache": "Cause",
      "Anordnung durch AG / Architekt": "Instruction by Client / Architect",
      "Geänderte Gegebenheiten vor Ort": "Changed local conditions",
      "Widerspruch in Planungsunterlagen": "Contradiction in planning documents",
      "Sonstiges": "Other",
      "Termin": "Schedule",
      "Verzögerung erwartet": "Delay expected",
      "2–3 Tage Verzögerung erwartet": "2–3 days delay expected",
      "Keine Verzögerung": "No delay",
      "Wir haben beim Aushub auf minus zwei vierzig Fels angetroffen. Das war nicht im LV vorgesehen, da steht nur Bodenklasse drei bis fünf. Der Bauleiter hat angeordnet, dass wir mit nem größeren Bagger und Meißel weitermachen. Die Anordnung ist BL-44. Die Felskante zieht sich quer durch die ganze Baugrube B.":
        "During excavation, we encountered rock at minus two forty. That was not in the BoQ, it only says soil excavation class three to five. The site manager instructed us to continue with a larger excavator and a breaker. The instruction is BL-44. The rock edge runs across the entire foundation pit B.",
      "Fels / stark verfestigter Boden (BK 6–7)":
        "rock / strongly compacted soil (class 6-7)",
      "Baugrube B, Tiefe −2,40 m":
        "foundation pit B, depth −2.40 m",
      "LV 02.03.0010 — Bodenaushub Bodenklasse 3–5":
        "LV 02.03.0010 — Soil excavation class 3–5",
      "Tatsächliche Bodenklasse weicht vom LV ab":
        "Actual soil class deviates from bill of quantities",
      "BL-44 — Fortführung mit Meißelverfahren":
        "BL-44 — continuation with breaker method",
      "+1.000 m³ Mehraushub":
        "+1,000 m³ additional excavation",
      "Foto der Felskante mit Maßstab":
        "photo of the rock edge with scale",
      "Tiefenmessung verifiziert":
        "depth measurement verified",
      "Tiefenmessung bestätigen (−2,40 m)":
        "confirm depth measurement (−2.40 m)",
      "Anordnung BL-44 verknüpfen":
        "link instruction BL-44",
      "GPS-Position erfasst":
        "GPS location captured",
      "Wetter & Bedingungen":
        "weather & conditions",
      "Sprich frei über das Ereignis...":
        "Speak freely about the event...",
      "Aufnahme läuft...":
        "Recording in progress...",
      "Sprachaufzeichnung":
        "Voice recording",
      "Sprachnotiz & Protokoll":
        "Voice note & transcript",
      "Rissbildung Bodenplatte A1":
        "Crack formation base slab A1",
      "Mögliche Abweichung":
        "Possible deviation",
      "Foto aufnehmen":
        "Take photo",
      "Was":
        "What",
      "Vollständiger Nachweis (100%)":
        "Complete evidence (100%)",
      "Beschreibe die Abweichung":
        "Describe the deviation",
      "Entwurf wird erstellt...":
        "Preparing draft...",
      "Strukturierung...":
        "Structuring...",
      "Sprachaufnahme wird verarbeitet...":
        "Processing voice recording...",
      "Analyse läuft...":
        "Analyzing...",
      "Erforderliche Nachweise":
        "Required evidence",
      "Sprachaufzeichnung beenden":
        "Stop recording",
      "Abweichung melden":
        "Report deviation",
      "Aufgabe: Foto der Felskante mit Maßstab":
        "Task: Photo of rock edge with scale",
      "Abweichung aufnehmen":
        "Record deviation",
      "Automatisch":
        "Auto",
      "Sensor":
        "Sensor",
      "Vom Bausoll-Abgleich zur prüffähigen Nachtragsakte.":
        "From contract-scope comparison to an auditable change-order file.",
      "Ein Nachtrag. Drei Rollen. Drei Geräte.":
        "One change order. Three roles. Three devices.",
      "Technischer Nachtrag": "Technical change order",
      "Aktueller Nachtrag": "Active change order",
      "Neubau Verwaltungsgebäude · Baufeld B":
        "New administrative building · Site B",
      "Aushub Baugrube · Tiefbau": "Foundation pit excavation · civil works",
      "Felsaushub Baufeld B": "Rock excavation · Site B",
      "Beim Aushub der Baugrube wird auf −2,40 m Fels / stark verfestigter Boden angetroffen — nicht im LV vorgesehen.":
        "During foundation excavation, rock / strongly compacted soil is encountered at −2.40 m — not included in the bill of quantities.",
      "Bodenaushub Bodenklasse 3–5": "Soil excavation class 3–5",
      "geschuldete Leistung laut LV": "contracted scope per bill of quantities",
      "Fels / stark verfestigter Boden BK 6–7":
        "rock / strongly compacted soil class 6–7",
      "größerer Bagger + Meißelverfahren": "larger excavator + breaker method",
      "Anordnung BL‑44 verknüpft": "instruction BL‑44 linked",
      "Wetter trocken": "weather dry",
      "Baugrube B": "foundation pit B",
      "Tiefe −2,40 m": "depth −2.40 m",
      "LKW-Zufahrt Nord blockiert": "truck access north blocked",
      "Aufmaß Schalung Abschnitt B2": "measurement formwork section B2",
      "Rissbildung Bodenplatte A1": "crack formation base slab A1",
      "Foto mit Maßstab": "photo with scale",
      "Tiefe dokumentiert": "depth documented",
      "Anordnung verknüpfen": "link instruction",
      "kurze Notiz ergänzen": "add short note",
      "Felskante läuft quer durch Baugrube B. Aushub mit Standardgerät nicht fortsetzbar; Bauleiter ordnet Fortführung mit Meißel an.":
        "The rock edge runs across foundation pit B. Excavation cannot continue with standard equipment; the site manager orders continuation with a breaker.",
      "Nachweis Tiefenmaß fehlt": "depth measurement proof missing",
      "Frist Nachtragsankündigung § 2 Abs. 5 VOB/B in 4 Tagen":
        "change-order notice deadline § 2(5) VOB/B in 4 days",
      "LV-Bezug bestätigen": "confirm bill-of-quantities reference",
      "Tiefenmaß-Aufmaß anhängen": "attach depth measurement record",
      "Nachtragsankündigung als versendet markieren":
        "mark change-order notice as sent",
      "Urkalkulation fortschreiben": "extend the original cost calculation",
      "NT‑02.03.F · Felsaushub BK 6–7":
        "CO‑02.03.F · rock excavation class 6–7",
      "Geräte-/Lohnansätze aus Urkalkulation":
        "equipment/labor rates from original calculation",
      "der Höhe nach belastbar": "defensible on quantum",
      Kausalität: "causality",
      "Fristwahrung (§ 2 Abs. 5 VOB/B)": "deadline preserved (§ 2(5) VOB/B)",
      "LV-/Vertragsbezug": "BoQ/contract reference",
      Urkalkulationsbezug: "original-calculation reference",
      "Nachweise vollständig": "Evidence complete",
      "Gegengezeichnete Anordnung BL‑44 in Begründung referenzieren":
        "reference countersigned instruction BL‑44 in the justification",
      Deckblatt: "cover sheet",
      Sachverhalt: "facts",
      "Bausoll / Bau-Ist": "contracted scope / actual site condition",
      Nachweise: "evidence",
      Mengen: "quantities",
      "Kalkulation / Urkalkulationsbezug":
        "calculation / original-cost reference",
      "Begründung § 2 VOB/B": "justification § 2 VOB/B",
      Bausoll: "contracted scope",
      "Bau-Ist": "actual site condition",
      Abweichung: "deviation",
      "Menge/Kosten": "quantity/cost impact",
      "prüffähige Nachtragsakte": "auditable change-order file",
      Nachtragsakte: "change-order file",
      Nachtrag: "change order",
      Baustelle: "Site",
      Kaufmännisch: "Commercial",
      Recht: "Legal",
      "Polier / Bauleiter": "foreman / site manager",
      "KBL / Projektleitung": "commercial project lead",
      "Legal / Nachtragsmanager": "legal / change-order manager",
      Übergabe: "handoff",
      Mobile: "mobile",
      Desktop: "desktop",
      Laptop: "laptop",
      "Ereignisse Baustelle": "site events",
      Ereignisse: "events",
      Ereignis: "event",
      Polier: "foreman",
      "+ Ereignis erfassen": "+ Capture event",
      Heute: "Today",
      Neu: "New",
      Prüfung: "Review",
      Entwurf: "Draft",
      Info: "Info",
      OK: "OK",
      "Kamera · Auto-Metadaten": "Camera · auto metadata",
      "Felskante dokumentieren": "Document rock edge",
      "Mögliche Abweichung erkannt": "Possible deviation detected",
      "Das Ereignis passt zu": "This event matches",
      "Dokumentiere jetzt, was später prüffähig sein muss.":
        "Document now what must be auditable later.",
      "Dokumentiere jetzt, was später": "Document now what must later be",
      "was später prüffähig sein muss.": "what must be auditable later.",
      "prüffähig sein muss.": "must be auditable.",
      Dokumentiere: "Document",
      Notiz: "note",
      "An Kaufmännisch übergeben": "Hand off to Commercial",
      Übermittelt: "Transmitted",
      erfasst: "captured",
      "Übergabe anzeigen": "Show handoff",
      "Übergabe an die kaufmännische Leitung": "Handoff to the commercial lead",
      "Nachtrag-Dashboard": "change-order dashboard",
      "Offene Nachträge": "Open change orders",
      offen: "open",
      Volumen: "volume",
      Fristen: "deadlines",
      Titel: "title",
      Status: "status",
      Frist: "deadline",
      Wert: "value",
      "Mehrstahl Decke C": "additional rebar slab C",
      Tage: "days",
      "Provisorische Entwässerung": "temporary drainage",
      "Eingang von Baustelle": "incoming from site",
      öffnen: "open",
      "N‑204 öffnen": "Open N‑204",
      "Bausoll ↔ Bau-Ist": "Contracted scope ↔ actual condition",
      "ABW.": "DEV.",
      Leistung: "scope item",
      Menge: "quantity",
      Befund: "finding",
      Tiefe: "depth",
      Mehrmenge: "additional quantity",
      Verfahren: "method",
      "Foto Felskante": "rock-edge photo",
      Anordnung: "instruction",
      "Tiefenmaß?": "depth proof?",
      Vollständigkeit: "completeness",
      "Nachweise prüfen": "Check evidence",
      "Fehlende Nachweise zeigen": "show missing evidence",
      "Nachweise vervollständigen": "Complete evidence",
      "Nachweise vollständig": "Evidence complete",
      "Fehlende Nachweise ergänzen": "Add missing evidence",
      "Urkalkulation-Fortschreibung": "Original-cost extension",
      "Neue Position": "new item",
      "abgeleiteter EP": "derived unit price",
      "Damit ist der Nachtrag nicht nur dem Grunde nach plausibel, sondern":
        "This makes the change order plausible not only on entitlement, but also",
      "Nachtragssumme ≈": "change-order amount ≈",
      "Zur rechtlichen Prüfung übergeben": "Hand off to legal review",
      "rechtlichen Prüfung": "legal review",
      "95 % bereit": "95% ready",
      "Abweichung, Nachweise, Mengen und Urkalkulationsbezug sind strukturiert. Die Akte geht jetzt an Recht zur rechtlichen Freigabe.":
        "Deviation, evidence, quantities and original-cost reference are structured. The file now goes to Legal for sign-off.",
      "Die Akte geht jetzt an Recht zur rechtlichen Freigabe.":
        "The file now goes to Legal for sign-off.",
      "rechtlichen Freigabe": "legal sign-off",
      "Bausoll/Bau-Ist geklärt": "scope/actual comparison resolved",
      "Frist gewahrt": "deadline preserved",
      "An Recht übergeben": "Hand off to Legal",
      "Rechtliche Freigabe": "Legal sign-off",
      Freigabe: "approval",
      "Freigabe-Queue": "approval queue",
      "1 Nachtragsakte zur Freigabe": "1 change-order file for approval",
      "1 offener Prüfpunkt": "1 open review item",
      Öffnen: "Open",
      "Rechtliche Prüfung": "Legal review",
      "Belastbarkeit prüfen": "Review defensibility",
      "1 offen": "1 open",
      "Formulierung bestätigen": "Confirm wording",
      "Letzter Prüfpunkt erledigt": "Final review item completed",
      Begründungsentwurf: "Draft justification",
      "Die angetroffene Bodenklasse": "The encountered soil class",
      "weicht vom vertraglich geschuldeten": "deviates from the contracted",
      " ab. Die geänderte Leistung wurde angeordnet und fristgerecht angekündigt.":
        ". The changed work was instructed and announced within the deadline.",
      "Die geänderte Leistung wurde angeordnet und fristgerecht angekündigt.":
        "The changed work was instructed and announced within the deadline.",
      "geänderte Leistung": "changed work",
      angeordnet: "instructed",
      fristgerecht: "within the deadline",
      "Als belastbar bestätigen & freigeben": "Confirm defensible & approve",
      "Belastbar – freigegeben": "Defensible – approved",
      "Die prüffähige Nachtragsakte ist bereit für Export und Versand.":
        "The auditable change-order file is ready for export and dispatch.",
      "Legal sign-off": "legal sign-off",
      "Nachtragsakte exportieren (PDF)": "Export change-order file (PDF)",
      Weiter: "Next",
      Dokumentvorschau: "document preview",
      "Prüffähige Nachtragsakte": "Auditable change-order file",
      Prüffähige: "auditable",
      enthalten: "included",
      Nachtragssumme: "change-order amount",
      "Das Baustellenereignis wurde klassifiziert und die Nachweise den Prüfkategorien zugeordnet.":
        "The site event has been classified and evidence assigned to review categories.",
      "dem Grunde nach": "on entitlement",
      "der Höhe nach": "on quantum",
      "Anspruchsbegründung": "Entitlement basis",
      "Preisnachweis": "Pricing evidence",
      "Fotos": "Photos",
      "Aufmaß": "Measurement record",
      "Urkalkulation": "Original costing",
      "Kein Nachweis": "No evidence",
      "Kritisch": "Critical",
      "Offen": "Open",
      "Nachweisstruktur": "Evidence structure",
      "Kostennachweis": "Cost evidence",
      "Fotos Felskante + Maßstab": "Rock edge photos + scale",
      "BL-44 Meißelverfahren": "BL-44 breaker method",
      "Geräte-/Lohnansätze": "equipment/labor rates",
      "Preisbasis": "price basis",
      "Keine AG-Gegenzeichnung": "No client countersignature",
      "Nicht AG-bestätigt": "Not confirmed by client",
      "Meißelarbeiten, Kolonne": "Chiseling work, crew",
      "30t Bagger + Hydraulikhammer": "30t excavator + hydraulic hammer",
      "Radlader Materialtransport": "Wheel loader transport",
      "Abtransport Felsgestein": "Rock material removal",
      "Nebenarbeiten pauschal": "Incidental work lump sum",
      "BGK / AGK / Wagnis & Gewinn": "Site overhead / company overhead / risk & profit",
      "Regiebericht nicht gegengezeichnet": "Site report not countersigned",
      "Gerätestunden nicht bestätigt": "Equipment hours not confirmed",
      "Nicht gegengezeichnet": "Not countersigned",
      "Aufmaß nicht AG-bestätigt": "Measurement record not confirmed by client",
      "Pauschalposition ohne belastbaren Nachweis": "Lump-sum item without traceable evidence",
      "Zuschlagslogik nur teilweise nachvollziehbar": "Surcharge logic only partially traceable",
      "BÜ-Gegenzeichnung Regiebericht anfordern": "Request countersignature on site report",
      "Stundenfreigabe oder BÜ-Bestätigung ergänzen": "Add hour release or site confirmation",
      "Regiebericht gegenzeichnen lassen": "Have site report countersigned",
      "Aufmaß bestätigen lassen": "Have measurement record confirmed",
      "Tätigkeiten aufschlüsseln oder Nachweis ergänzen": "Break down activities or add evidence",
      "EFB-Bezug und Zuschlagsbasis erläutern": "Clarify EFB reference and surcharge basis",
      "LV-Auszug": "BoQ extract",
      "Anordnung / Protokoll": "Instruction / minutes",
      "Neu starten": "Start over",
      "AUTO: GPS · ZEIT · TIEFE": "AUTO: GPS · TIME · DEPTH",
      "app.nachweis.bau/nachtraege": "app.nachweis.bau/change-orders",
      "app.nachweis.bau/freigabe": "app.nachweis.bau/approval",
      SHOT: "SHOT",
      FOTO: "PHOTO",
      "Pfeiltasten ← → oder klicken": "Arrow keys ← → or click",
      Starten: "Start",
    },
  },
  de: {
    static: {
      brandTag: "Nachtragsmanagement",
      navHint: "Tastatur: ← zurück · →/Enter weiter · R Neustart",
      back: "← Zurück",
      next: "Weiter →",
      restart: "Restart",
      restartNext: "Neu starten ↻",
      toast: "Nachtragsakte als PDF exportiert",
    },
    replace: {},
  },
};

let currentLanguage = "de";
